GET http://localhost:3005/api/staffs

###
DELETE http://localhost:3005/api/staffs/fc2fef11-bb8d-41b7-9507-b32895fa26a0
###
POST http://localhost:3005/api/staffs
Content-Type: application/json

{
    "firstname": "Jeph",
    "lastname": "Mane",
    "email": "jeff@test.io",
    "primary_contact": "020030301",
    "dob": "1990/06/25",
    "residence": "Mpraeso",
    "password": "emily",
    "levelName": [
        {
            "name": "JHS 2"
        },
        {
            "name": "Primary 2"
        }
    ],
    "subjectName":[
        {
            "subjectName": "English Language"
        },
        {
            "subjectName": "Mathematics"
        }
    ]
}

###
POST http://localhost:3005/api/questions
Content-Type: application/json

{
    "title": "English",
    "timeLimit": 30,
    "categoryId": "d0d286dd-a221-4881-8cd4-d905179f3973",
    "deadline": "2023/10/29",
    "classId": "30406c1f-aa95-4b84-81c0-43edfe947fe4",
    "questionTexts":[
        {
            "question":"Ha_ _iness",
            "answerChoices": [
                {
                    "choice": "pp",
                    "isCorrect": true
                },
                {
                    "choice": "rv"
                },
                {
                    "choice": "su"
                },
                {
                    "choice": "rp"
                }
            ]
        },
        {
            "question":"Aero_ _ane",
            "answerChoices": [
                {
                    "choice": "pl",
                    "isCorrect": true
                },
                {
                    "choice": "rv"
                },
                {
                    "choice": "su"
                },
                {
                    "choice": "rp"
                }
            ]
        },
        {
            "question":"Me_ _ _ge",
            "answerChoices": [
                {
                    "choice": "pp",
                    "isCorrect": false
                },
                {
                    "choice": "ssa",
                    "isCorrect": true
                },
                {
                    "choice": "su"
                },
                {
                    "choice": "rp"
                }
            ]
        },
        {
            "question":"Gh_n_",
            "answerChoices": [
                {
                    "choice": "a and a",
                    "isCorrect": true
                },
                {
                    "choice": "rv and a"
                },
                {
                    "choice": "su and a"
                },
                {
                    "choice": "rp and a"
                }
            ]
        }
    ]
}

###
POST http://localhost:3005/api/auth/login
Content-Type: application/json

{
    "userId": "admin",
    "password": "admin"
}

###
POST http://localhost:3005/api/students
Content-Type: application/json

{
    "firstname": "Abdul",
    "lastname": "Karim",
    "dob": "2002/12/19",
    "residence": "Kumasi",
    "classId": "30406c1f-aa95-4b84-81c0-43edfe947fe4",
    "password": "biggy"
}