GET http://localhost:3005/api/questions

###
DELETE http://localhost:3005/api/questions/33f49134-6334-40fe-90ed-2f8a45c90356
###
POST http://localhost:3005/api/staffs
Content-Type: application/json

{
    "firstname": "Emily",
    "middlename": "Doe",
    "lastname": "Smith",
    "email": "emily@test.io",
    "primary_contact": "020030300",
    "dob": "1990/06/25",
    "residence": "Mpraeso"
}

###
POST http://localhost:3005/api/questions
Content-Type: application/json

{
    "title": "English",
    "timeLimit": 30,
    "categoryId": "85c0ada3-321b-4d98-9e78-d33b89daa533",
    "deadline": "2023/10/29",
    "classId": "e23a0727-a533-490c-9226-1f8cb75bbd14",
    "questionTexts":[
        {
            "question":"Ha_ _iness",
            "answerChoices": [
                {
                    "choice": "pp",
                    "isCorrect": true
                },
                {
                    "choice": "rv"
                },
                {
                    "choice": "su"
                },
                {
                    "choice": "rp"
                }
            ]
        },
        {
            "question":"Aero_ _ane",
            "answerChoices": [
                {
                    "choice": "pl",
                    "isCorrect": true
                },
                {
                    "choice": "rv"
                },
                {
                    "choice": "su"
                },
                {
                    "choice": "rp"
                }
            ]
        },
        {
            "question":"Me_ _ _ge",
            "answerChoices": [
                {
                    "choice": "pp",
                    "isCorrect": false
                },
                {
                    "choice": "ssa",
                    "isCorrect": true
                },
                {
                    "choice": "su"
                },
                {
                    "choice": "rp"
                }
            ]
        },
        {
            "question":"Gh_n_",
            "answerChoices": [
                {
                    "choice": "a and a",
                    "isCorrect": true
                },
                {
                    "choice": "rv and a"
                },
                {
                    "choice": "su and a"
                },
                {
                    "choice": "rp and a"
                }
            ]
        }
    ]
}